// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYyIp9HCqgKA9Jhq19rfbKM2Z8_PdSyE',
    appId: '1:376725753941:web:5dde5dd52037e7c9eac4dc',
    messagingSenderId: '376725753941',
    projectId: 'solarpanelresearch-3fcb9',
    authDomain: 'solarpanelresearch-3fcb9.firebaseapp.com',
    databaseURL: 'https://solarpanelresearch-3fcb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solarpanelresearch-3fcb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOfA3lJiS0o1hRkhzNvkypOiMoq3csDHk',
    appId: '1:376725753941:android:2f58343594d3ec1ceac4dc',
    messagingSenderId: '376725753941',
    projectId: 'solarpanelresearch-3fcb9',
    databaseURL: 'https://solarpanelresearch-3fcb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solarpanelresearch-3fcb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2XVawzsZ3n0DPDzDUrXCrpO9uJfykzH0',
    appId: '1:376725753941:ios:5c4a096cd99fed50eac4dc',
    messagingSenderId: '376725753941',
    projectId: 'solarpanelresearch-3fcb9',
    databaseURL: 'https://solarpanelresearch-3fcb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solarpanelresearch-3fcb9.appspot.com',
    iosClientId: '376725753941-adjnp613h7a5pr36mpsvgpmnt0rpt73o.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarPanelResearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2XVawzsZ3n0DPDzDUrXCrpO9uJfykzH0',
    appId: '1:376725753941:ios:5c4a096cd99fed50eac4dc',
    messagingSenderId: '376725753941',
    projectId: 'solarpanelresearch-3fcb9',
    databaseURL: 'https://solarpanelresearch-3fcb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solarpanelresearch-3fcb9.appspot.com',
    iosClientId: '376725753941-adjnp613h7a5pr36mpsvgpmnt0rpt73o.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarPanelResearch',
  );
}
